### ISSUE TITLE
Example JS code

### ISSUE THREAD

**Issue by joshhornby** [timmh/react-native-camera#5]
Do you have an example how we can use this in an `.js` file?

After running the setup outlined in the android folder, I get the following error

`ReactCameraView has no propType for native prop ReactCameraView.scaleX of native type number`

When trying to `require('react-native-camera')`

Thanks

**Comment by timmh** [comment]
Please have a look at the [android readme](https://github.com/timmh/react-native-camera/blob/master/android/README.md) for instructions on how to add this to your project.
You can then use the [index.android.js](https://github.com/timmh/react-native-camera/blob/master/example/index.android.js) in the [example](https://github.com/timmh/react-native-camera/tree/master/example) as a reference.

**Comment by joshhornby** [comment]
Can you confirm that the example works locally for you? I ran into some errors when trying to boot up the app. Eg.

`“Invariant Violation: Application AwesomeProject has not been registered”`

**Comment by joshhornby** [comment]
After copying the instructions in [this readme](https://github.com/timmh/react-native-camera/tree/master/example) on running the application will not boot in the emulator, instead just crashes straight away. If you tell me how I can get some logs for this I can post.

**Comment by timmh** [comment]
You could try running the example project and see if that is working for you.
`Invariant Violation: Application AwesomeProject has not been registered` means that you have a javascript error somewhere prior to you `AppRegistry.registerComponent` call.
If you do not find the error please post your application's logs (for example via [pidcat](https://github.com/JakeWharton/pidcat): `pidcat com.awesomeproject`)

**Comment by joshhornby** [comment]
After running the application in the example folder, I got the following error:

```
                            Process com.reactnativecameraexample created for activity com.reactnativecameraexample/.MainActivi
                            ty
                            PID: 2073   UID:    GIDs: 

                    art  I  Not late-enabling -Xcheck:jni (already on)
         OpenGLRenderer  D  Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                         D  HostConnection::get() New Host Connection established 0xb3eb3e50, tid 2073
                  Atlas  D  Validating map...
                         D  HostConnection::get() New Host Connection established 0xb3eb3f20, tid 2089
         OpenGLRenderer  I  Initialized EGL, version 1.4
                         D  Enabling debug mode 0
          EGL_emulation  W  eglSurfaceAttrib not implemented
         OpenGLRenderer  W  Failed to set EGL_SWAP_BEHAVIOR on surface 0xb3f1dc80, error=EGL_SUCCESS
          Choreographer  I  Skipped 44 frames!  The application may be doing too much work on its main thread.
          unknown:React  W  Unable to dispatch keyboard events in JS as the react instance has not been attached
          EGL_emulation  W  eglSurfaceAttrib not implemented
         OpenGLRenderer  W  Failed to set EGL_SWAP_BEHAVIOR on surface 0xb3f1dca0, error=EGL_SUCCESS
                    art  I  Background partial concurrent mark sweep GC freed 2404(131KB) AllocSpace objects, 0(0B) LOS objects
                            , 51% free, 971KB/1995KB, paused 7.392ms total 163.830ms
                         I  Thread[1,tid=2073,WaitingForJniOnLoad,Thread*=0xb3c25400,peer=0x74cdc000,"main"] recursive attempt 
                            to load library "/data/app/com.reactnativecameraexample-2/lib/x86/libreactnativejni.so"
                         I  Background sticky concurrent mark sweep GC freed 9023(503KB) AllocSpace objects, 0(0B) LOS objects,
                             31% free, 1369KB/1995KB, paused 7.017ms total 18.878ms
          ReactNativeJS  W  'Warning: Native component for "RCTModalHostView" does not exist'
                         D  'Running application "ReactNativeCameraExample" with appParams: {"initialProps":{},"rootTag":1}. __
                            DEV__ === true, development-level warning are ON, performance optimizations are OFF'
                         W  'Warning: Failed propType: Invariant Violation: Invalid props.style key `textAlign` supplied to `To
                            uchableHighlight`.\nBad object: {\n  "position": "absolute",\n  "height": 50,\n  "left": 50,\n  "bo
                            ttom": 20,\n  "right": 50,\n  "backgroundColor": "#FFFFFF",\n  "borderRadius": 20,\n  "textAlign": 
                            "center"\n}\nValid keys: [\n  "width",\n  "height",\n  "top",\n  "left",\n  "right",\n  "bottom",\n
                              "margin",\n  "marginVertical",\n  "marginHorizontal",\n  "marginTop",\n  "marginBottom",\n  "marg
                            inLeft",\n  "marginRight",\n  "padding",\n  "paddingVertical",\n  "paddingHorizontal",\n  "paddingT
                            op",\n  "paddingBottom",\n  "paddingLeft",\n  "paddingRight",\n  "borderWidth",\n  "borderTopWidth"
                            ,\n  "borderRightWidth",\n  "borderBottomWidth",\n  "borderLeftWidth",\n  "position",\n  "flexDirec
                            tion",\n  "flexWrap",\n  "justifyContent",\n  "alignItems",\n  "alignSelf",\n  "flex",\n  "transfor
                            m",\n  "transformMatrix",\n  "backfaceVisibility",\n  "backgroundColor",\n  "borderColor",\n  "bord
                            erTopColor",\n  "borderRightColor",\n  "borderBottomColor",\n  "borderLeftColor",\n  "borderRadius"
                            ,\n  "borderTopLeftRadius",\n  "borderTopRightRadius",\n  "borderBottomLeftRadius",\n  "borderBotto
                            mRightRadius",\n  "borderStyle",\n  "opacity",\n  "overflow",\n  "shadowColor",\n  "shadowOffset",\
                            n  "shadowOpacity",\n  "shadowRadius"\n] Check the render method of `ReactNativeCameraExample`.'
                         W  'Warning: Failed propType: Invariant Violation: Invalid props.style key `textAlign` supplied to `Vi
                            ew`.\nBad object: {\n  "backgroundColor": "#FFFFFF",\n  "position": "absolute",\n  "height": 50,\n 
                             "left": 50,\n  "bottom": 20,\n  "right": 50,\n  "borderRadius": 20,\n  "textAlign": "center"\n}\nV
                            alid keys: [\n  "width",\n  "height",\n  "top",\n  "left",\n  "right",\n  "bottom",\n  "margin",\n 
                             "marginVertical",\n  "marginHorizontal",\n  "marginTop",\n  "marginBottom",\n  "marginLeft",\n  "m
                            arginRight",\n  "padding",\n  "paddingVertical",\n  "paddingHorizontal",\n  "paddingTop",\n  "paddi
                            ngBottom",\n  "paddingLeft",\n  "paddingRight",\n  "borderWidth",\n  "borderTopWidth",\n  "borderRi
                            ghtWidth",\n  "borderBottomWidth",\n  "borderLeftWidth",\n  "position",\n  "flexDirection",\n  "fle
                            xWrap",\n  "justifyContent",\n  "alignItems",\n  "alignSelf",\n  "flex",\n  "transform",\n  "transf
                            ormMatrix",\n  "backfaceVisibility",\n  "backgroundColor",\n  "borderColor",\n  "borderTopColor",\n
                              "borderRightColor",\n  "borderBottomColor",\n  "borderLeftColor",\n  "borderRadius",\n  "borderTo
                            pLeftRadius",\n  "borderTopRightRadius",\n  "borderBottomLeftRadius",\n  "borderBottomRightRadius",
                            \n  "borderStyle",\n  "opacity",\n  "overflow",\n  "shadowColor",\n  "shadowOffset",\n  "shadowOpac
                            ity",\n  "shadowRadius"\n] Check the render method of `TouchableHighlight`.'
                         W  'Warning: Failed propType: Invariant Violation: Invalid props.style key `textAlign` supplied to `RC
                            TView`.\nBad object: {\n  "backgroundColor": "#FFFFFF",\n  "position": "absolute",\n  "height": 50,
                            \n  "left": 50,\n  "bottom": 20,\n  "right": 50,\n  "borderRadius": 20,\n  "textAlign": "center"\n}
                            \nValid keys: [\n  "width",\n  "height",\n  "top",\n  "left",\n  "right",\n  "bottom",\n  "margin",
                            \n  "marginVertical",\n  "marginHorizontal",\n  "marginTop",\n  "marginBottom",\n  "marginLeft",\n 
                             "marginRight",\n  "padding",\n  "paddingVertical",\n  "paddingHorizontal",\n  "paddingTop",\n  "pa
                            ddingBottom",\n  "paddingLeft",\n  "paddingRight",\n  "borderWidth",\n  "borderTopWidth",\n  "borde
                            rRightWidth",\n  "borderBottomWidth",\n  "borderLeftWidth",\n  "position",\n  "flexDirection",\n  "
                            flexWrap",\n  "justifyContent",\n  "alignItems",\n  "alignSelf",\n  "flex",\n  "transform",\n  "tra
                            nsformMatrix",\n  "backfaceVisibility",\n  "backgroundColor",\n  "borderColor",\n  "borderTopColor"
                            ,\n  "borderRightColor",\n  "borderBottomColor",\n  "borderLeftColor",\n  "borderRadius",\n  "borde
                            rTopLeftRadius",\n  "borderTopRightRadius",\n  "borderBottomLeftRadius",\n  "borderBottomRightRadiu
                            s",\n  "borderStyle",\n  "opacity",\n  "overflow",\n  "shadowColor",\n  "shadowOffset",\n  "shadowO
                            pacity",\n  "shadowRadius"\n] Check the render method of `View`.'
          EGL_emulation  W  eglSurfaceAttrib not implemented
         OpenGLRenderer  W  Failed to set EGL_SWAP_BEHAVIOR on surface 0xb3f1dc80, error=EGL_SUCCESS
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.reactnativecameraexample, PID: 2073
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setP
                            reviewDisplay(android.view.SurfaceHolder)' on a null object reference
                         E      at com.lwansbrough.ReactCamera.ReactCameraView.surfaceCreated(ReactCameraView.java:38)
                         E      at android.view.SurfaceView.updateWindow(SurfaceView.java:580)
                         E      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
                         E      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                         E      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1970)
                         E      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                         E      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                         E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                         E      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                         E      at android.view.Choreographer.doFrame(Choreographer.java:550)
                         E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                         E      at android.os.Handler.handleCallback(Handler.java:739)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5257)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by joshhornby** [comment]
This was due to my emulator not being set up correctly. The package only supports the rear facing camera. Is there any plans to add the front facing camera?

**Comment by timmh** [comment]
Yes, I plan to write a new camera manager that supports different cameras and multiple component instances per camera this week. Will update you on the progress in this issue.

**Comment by joshhornby** [comment]
Brilliant. Look forward to seeing it :)

**Comment by machard** [comment]
I had to add some proptypes to make it work with RN 0.13.2. otherwise i also get 'ReactCameraView has no propType for native prop ReactCameraView.scaleX of native type number'

see also
https://github.com/corymsmith/react-native-icons/pull/120

**Comment by timmh** [comment]
@machard this issue should be fixed with 3f9080
@joshhornby unfortunately the rewrite takes longer than i thought, hope to get this out this weekend.

**Comment by timmh** [comment]
@joshhornby the development branch now contains a type prop which you can use like the one for ios to change the camera used. But there is a problem with the app crashing when you change the type prop a second time, so you should use a fixed value for now.

**Comment by hunteredwards** [comment]
@timmh First off, thank you for this so much! I pulled down the development branch and when I try to run, it keeps failing because of `addPackage(new ReactCameraPackage(this))` which expects no arguments. When I remove `this` and rerun, none of the new functionality seems to work. Any suggestions?

**Comment by timmh** [comment]
@hunteredwards are you sure that you are using the development branch?
`new ReactCameraPackage(this)` [should work](https://github.com/timmh/react-native-camera/blob/development/android/src/main/java/com/lwansbrough/ReactCamera/ReactCameraPackage.java#L19).
You can install the branch via npm: `npm install https://github.com/timmh/react-native-camera.git#development`.

**Comment by hunteredwards** [comment]
@timmh I just reinstalled the dev branch twice, and it finally worked! Thanks again for your work on this. Absolutely awesome.

Is zoom functionality and/or tap-to-focus on the roadmap at all?

**Comment by timmh** [comment]
@hunteredwards happy to hear that its working for you.
zomm and tap-to-focus is definitely on the roadmap but there are many features with higher priority right now.

**Comment by joshhornby** [comment]
@timmh Sorry, just catching up with this. Great work so far :+1: 

Do you have a roadmap of features and also the know bugs? The reason I ask is I need to use this on a large project so just need to know the full project landscape before starting.

**Comment by timmh** [comment]
@joshhornby I just added a roadmap to the readme. That includes most issues and missing features compared to the original project in the anticipated order of implementation.
